server:
    port: 8080
oracle:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:tghin:@192.168.1.101:1521:db01
        username: mybatisdemo
        password: mybatisdemopw