server:
    port: 8080
#spring:
#    aop:
#        proxy-target-class: true
oracle:
    datasource:
        driver_class_name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.1.101:1521:db01
        username: mybatisdemo
        password: mybatisdemopw